WebStoreProject/WebStoreProject/Controllers/OrdersAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebStoreProject.Models;

namespace WebStoreProject.Controllers
{
    [Authorize(Roles = "ROLE_ADMIN")]
    public class OrdersAdminController : Controller
    {
        private DBModel db;

        public OrdersAdminController()
        {
            db = new DBModel();
        }
        // GET: OrdersAdmin
        public ActionResult Index()
        {
            List<Order_details> orders = db.Order_details.ToList();
            return View(orders);
        }

        // GET: OrdersAdmin/Details/5
        public ActionResult Details(int id)
        {
            Order_details details = db.Order_details.Find(id);
            return View(details);
        }

        // GET: OrdersAdmin/Edit/5
        public ActionResult Edit(int id)
        {
            Order_details details = db.Order_details.Find(id);

            List<Payment> paymentTypes = db.Payment.ToList();
            ViewBag.PaymentTypes = new SelectList(paymentTypes, "Id", "Name");

            List<Delivery> deliveryTypes = db.Delivery.ToList();
            ViewBag.DeliveryTypes = new SelectList(deliveryTypes, "Id", "Name");

            List<Status> status = db.Status.ToList();
            ViewBag.Status = new SelectList(status, "Id", "Name");

            return View(details);
        }

        // POST: OrdersAdmin/Edit/5
        [HttpPost]
        public ActionResult Edit(Order_details order)
        {
            try
            {
                Order_details orderToEdit = db.Order_details.Find(order.Id);
                UpdateModel(orderToEdit);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebStoreProject/WebStoreProject/Views/OrdersAdmin/Details.cshtml
@model WebStoreProject.Models.Order_details

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Order.User.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Order.User.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Order.Payment.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Order.Payment.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Order.Shipment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Order.Shipment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Order.Delivery)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Order.Delivery.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Order.Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Order.Value)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

WebStoreProject/WebStoreProject/Views/OrdersAdmin/Edit.cshtml
@model WebStoreProject.Models.Order_details

@{
    ViewBag.Title = "Edit";
}

<h2><b>Customer:</b> @Model.Order.User.Name</h2>
<h2><b>Order value:</b> @Html.DisplayFor(model => model.Order.Value)</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.StatusID, ViewBag.Status as SelectList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StatusID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebStoreProject/WebStoreProject/Views/OrdersAdmin/Index.cshtml
@model IEnumerable<WebStoreProject.Models.Order_details>

<h2>Orders.</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Order.User.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Order.Payment.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Order.User.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Order.Payment.Name)
        </td>
        <td>
            <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Edit", "OrdersAdmin", new { id = item.Id })'">
                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                Edit
            </button>
            <button type="button" class="btn btn-info" onclick="location.href='@Url.Action("Details", "OrdersAdmin", new { id = item.Id })'">
                <i class="fa fa-search" aria-hidden="true"></i>
                Details
            </button>
        </td>
    </tr>
}

</table>