WebStoreProject/WebStoreProject/Models/ShoppingCart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebStoreProject.Models
{
    public class ShoppingCart
    {
        public Product Product { get; set; }
        public int Quantity { get; set; }

        public ShoppingCart(Product product, int quantity)
        {
            Product = product;
            Quantity = quantity;
        }
    }
}

WebStoreProject/WebStoreProject/Controllers/OrderController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebStoreProject.Models;

namespace WebStoreProject.Controllers
{
    public class OrderController : Controller
    {
        private DBModel db;

        public OrderController()
        {
            db = new DBModel();
        }
        // GET: Order
        public ActionResult Index()
        {
            ApplicationUser user = db.Users.Find(User.Identity.GetUserId());

            List<ShoppingCart> temp = (List<ShoppingCart>)Session["Cart"];
            double totalPrice = temp.Sum(x => x.Product.Price_brutto * x.Quantity);
            
            if(user.Discount.HasValue)
            {
                double discount = totalPrice * user.Discount.Value / 100;
                totalPrice = totalPrice - discount;
            }

            ViewBag.PriceToDisplay = String.Format("{0:N2}", totalPrice);
            if (User.Identity.IsAuthenticated)
            {
                if (user.Price_display.Equals("NETTO"))
                {
                    temp.ForEach(x => {
                        if (x.Product.Vat.Value == null)
                        {
                            x.Product.Vat.Value = 0;
                        }
                    });
                    double? nullableNetto = temp.Sum(x => ((x.Product.Price_brutto / (100 + x.Product.Vat.Value)) * 100) * x.Quantity);
                    double netto = 0;
                    if (nullableNetto.HasValue)
                    {
                        netto = nullableNetto.Value;
                    }

                    if (user.Discount.HasValue)
                    {
                        double discount = netto * user.Discount.Value / 100;
                        netto = netto - discount;
                    }

                    ViewBag.PriceToDisplay = String.Format("{0:N2}", Math.Truncate(netto * 100) / 100);
                    
                }
            }

            List<Payment> paymentTypes = db.Payment.ToList();
            ViewBag.PaymentTypes = new SelectList(paymentTypes, "Id", "Name");

            List<Delivery> deliveryTypes = db.Delivery.ToList();
            ViewBag.DeliveryTypes = new SelectList(deliveryTypes, "Id", "Name");

            Orders order = new Orders()
            {
                User = user,
                UserID = user.Id,
                Shipment = user.Address,
                Value = totalPrice
            };
            return View(order);
        }

        // GET: Order/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Order/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Order/Create
        [HttpPost]
        public ActionResult Create(Orders order)
        {
            try
            {
                List<ShoppingCart> listCart = (List<ShoppingCart>)Session["Cart"];
                db.Orders.Add(order);
                db.SaveChanges();
                
                foreach(ShoppingCart cart in listCart)
                {
                    Order_item orderItem = new Order_item()
                    {
                        OrderID = order.Id,
                        ProductID = cart.Product.Id,
                        Quantity = cart.Quantity
                    };
                    db.Order_item.Add(orderItem);
                    db.SaveChanges();
                }
                Session.Remove("Cart");

                Order_details orderDetails = new Order_details()
                {
                    Order = order,
                    StatusID = 1
                };
                db.Order_details.Add(orderDetails);
                db.SaveChanges();

                // tutaj wyslac na strone ze zamowienie zostalo zlozone i ze liste zamowien mozna zobaczyc np. w profilu
                // i oczywisice zrobic trzeba w profilu mozliwosc zobaczenia zamowien
                return RedirectToAction("Index", "Home", new { area = "" });
            }
            catch
            {
                // Error - Trzeba zrobic strone dla View ze blad wystapil albo jakas ogolna ze blad wystapil
                // bo jak teraz wywali errora gdzies to zwroci ze ta strona nie istnieje :P
                return View();
            }
        }

        // GET: Order/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Order/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Order/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Order/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebStoreProject/WebStoreProject/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebStoreProject.Models;

namespace WebStoreProject.Controllers
{
    public class ProductController : Controller
    {
        private DBModel db;

        public ProductController()
        {
            db = new DBModel();
        }

        // GET: Product
        public ActionResult Index()
        {
            List<Product> products = db.Product.ToList();

            if(User.Identity.IsAuthenticated)
            {
                ApplicationUser user = db.Users.Where(u => u.Email.Equals(User.Identity.Name)).First();
                ViewBag.PriceDisplay = user.Price_display;

                if (user.Price_display.Equals("NETTO"))
                {
                    products.ForEach(p => {
                        int abc = 0;
                        if(p.Vat != null)
                        {
                            abc = p.Vat.Value.Value;
                        }
                        
                        p.Price_brutto = (p.Price_brutto / (100 + abc)) * 100;
                    });
                    products.ForEach(p => p.Price_brutto = Math.Truncate(p.Price_brutto * 100) / 100);
                }
            }

            return View(products);
        }

        // GET: Product/Details/5
        public ActionResult Details(int id)
        {
            Product product = db.Product.Find(id);
            return View(product);
        }

        // GET: Product/Create
        public ActionResult Create()
        {
            List<VAT> vatList = db.VAT.ToList();
            ViewBag.VatList = new SelectList(vatList, "Id", "Value");

            List<Category> categories = db.Category.ToList();
            ViewBag.Categories = new SelectList(categories, "Id", "Name");

            return View();
        }

        // POST: Product/Create
        [HttpPost]
        public ActionResult Create(Product product, HttpPostedFileBase LogoImageFile, HttpPostedFileBase DetailsImageFile)
        {
            try
            {
                string logoFileName = Path.GetFileNameWithoutExtension(LogoImageFile.FileName);
                string logoExtension = Path.GetExtension(LogoImageFile.FileName);
                logoFileName = logoFileName + DateTime.Now.ToString("yymmssfff") + logoExtension;
                string logoImgPath = "~/Images/" + logoFileName;
                logoFileName = Path.Combine(Server.MapPath("~/Images/"), logoFileName);

                string detailsFileName = Path.GetFileNameWithoutExtension(DetailsImageFile.FileName);
                string detailsExtension = Path.GetExtension(DetailsImageFile.FileName);
                detailsFileName = detailsFileName + DateTime.Now.ToString("yymmssfff") + detailsExtension;
                string detailsImgPath = "~/Images/" + detailsFileName;
                detailsFileName = Path.Combine(Server.MapPath("~/Images/"), detailsFileName);

                LogoImageFile.SaveAs(logoFileName);
                DetailsImageFile.SaveAs(detailsFileName);

                product.LogoImagePath = logoImgPath;
                product.DetailsImagePath = detailsImgPath;
                db.Product.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Product/Edit/5
        [Authorize(Roles = "ROLE_ADMIN")]
        public ActionResult Edit(int id)
        {
            Product product = db.Product.Find(id);

            List<VAT> vatList = db.VAT.ToList();
            ViewBag.VatList = new SelectList(vatList, "Id", "Value");

            List<Category> categories = db.Category.ToList();
            ViewBag.Categories = new SelectList(categories, "Id", "Name");

            return View(product);
        }

        // POST: Product/Edit/5
        [HttpPost]
        [Authorize(Roles = "ROLE_ADMIN")]
        public ActionResult Edit(Product product, HttpPostedFileBase LogoImageFile, HttpPostedFileBase DetailsImageFile)
        {
            try
            {
                Product productToEdit = db.Product.Find(product.Id);

                if(LogoImageFile != null)
                {
                    string logoFileName = Path.GetFileNameWithoutExtension(LogoImageFile.FileName);
                    string logoExtension = Path.GetExtension(LogoImageFile.FileName);
                    logoFileName = logoFileName + DateTime.Now.ToString("yymmssfff") + logoExtension;
                    string logoImgPath = "~/Images/" + logoFileName;
                    logoFileName = Path.Combine(Server.MapPath("~/Images/"), logoFileName);
                    LogoImageFile.SaveAs(logoFileName);
                    productToEdit.LogoImagePath = logoImgPath;
                }

                if(DetailsImageFile != null)
                {
                    string detailsFileName = Path.GetFileNameWithoutExtension(DetailsImageFile.FileName);
                    string detailsExtension = Path.GetExtension(DetailsImageFile.FileName);
                    detailsFileName = detailsFileName + DateTime.Now.ToString("yymmssfff") + detailsExtension;
                    string detailsImgPath = "~/Images/" + detailsFileName;
                    detailsFileName = Path.Combine(Server.MapPath("~/Images/"), detailsFileName);
                    DetailsImageFile.SaveAs(detailsFileName);
                    productToEdit.DetailsImagePath = detailsImgPath;
                }

                TryUpdateModel(productToEdit);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Product/Delete/5
        [Authorize(Roles = "ROLE_ADMIN")]
        public ActionResult Delete(int id)
        {
            ViewBag.Error = false;
            Product product = db.Product.Find(id);
            return View(product);
        }

        // POST: Product/Delete/5
        [HttpPost]
        [Authorize(Roles = "ROLE_ADMIN")]
        public ActionResult Delete(Product product)
        {
            try
            {
                  Product productToDelete = db.Product.Find(product.Id);
                  db.Product.Remove(productToDelete);
                  db.SaveChanges();
                  return RedirectToAction("Index");
            }
            catch
            {
                Product productToDelete = db.Product.Find(product.Id);
                ViewBag.Error = true;
                ViewBag.ErrorMsg = "Some error occured! Contact with administration!";
                return View(productToDelete);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebStoreProject/WebStoreProject/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebStoreProject.Models;

namespace WebStoreProject.Controllers
{
    [Authorize]
    public class ShoppingCartController : Controller
    {
        private DBModel db;
        private string strCart = "Cart";

        public ShoppingCartController()
        {
            db = new DBModel();
        }

        // GET: ShoppingCart
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Delete(int id)
        {
            int position = GetProductIndex(id);
            List<ShoppingCart> listCart = (List<ShoppingCart>)Session[strCart];
            listCart.RemoveAt(position);
            return View("Index");
        }

        public ActionResult OrderNow(int id)
        {
            if(Session[strCart] == null)
            {
                List<ShoppingCart> listCart = new List<ShoppingCart>
                {
                    new ShoppingCart(db.Product.Find(id), 1)
                };
                Session[strCart] = listCart;
            }
            else
            {
                List<ShoppingCart> listCart = (List<ShoppingCart>)Session[strCart];
                if(IsProductAdded(id))
                {
                    int position = GetProductIndex(id);
                    listCart[position].Quantity++;
                } else
                {
                    listCart.Add(new ShoppingCart(db.Product.Find(id), 1));
                }
                Session[strCart] = listCart;
            }
            return View("Index");
        }

        private bool IsProductAdded(int id)
        {
            List<ShoppingCart> listCart = (List<ShoppingCart>)Session[strCart];
            foreach(ShoppingCart sc in listCart) 
            {
                if(sc.Product.Id == id)
                {
                    return true;
                }
            }
            return false;
        }

        private int GetProductIndex(int id)
        {
            List<ShoppingCart> listCart = (List<ShoppingCart>)Session[strCart];
            for(int i=0; i<listCart.Count; i++)
            {
                if (listCart[i].Product.Id == id) return i;
            }
            return -1;
        }

        public ActionResult Summary(FormCollection frc)
        {
            string[] quantities = frc.GetValues("cart.Quantity");
            List<ShoppingCart> listCart = (List<ShoppingCart>)Session[strCart];
            for(int i=0; i<listCart.Count; i++)
            {
                listCart[i].Quantity = Convert.ToInt32(quantities[i]);
            }

            Session[strCart] = listCart;
            ViewBag.Modal = true;

            return View("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebStoreProject/WebStoreProject/Views/ShoppingCart/Index.cshtml
@using WebStoreProject.Models;
@model IEnumerable<WebStoreProject.Models.ShoppingCart>
@{
    ViewBag.Title = "Index";
}

<h2>Shopping cart</h2>

@if (Session["Cart"] != null)
{
    using (Html.BeginForm("Summary", "ShoppingCart", FormMethod.Post))
    {
    <table class="table">
        <tr>
            <th>
                @Html.DisplayName("Product name")
            </th>
            <th>
                @Html.DisplayName("Quantity")
            </th>
            <th></th>
        </tr>

        @foreach (var cart in (List<ShoppingCart>)Session["Cart"])
        {
            <tr>
                <td>
                    @Html.ActionLink(cart.Product.Name, "Details", "Product", new { id = cart.Product.Id }, null)
                </td>
                <td>
                    @Html.EditorFor(modelItem => cart.Quantity, new { htmlAttributes = new { @class = "form-control", @min = "1" } })
                </td>
                <td>
                    <button type="button" class="close" onclick="location.href='@Url.Action("Delete", "ShoppingCart", new { id = cart.Product.Id })'">
                        &times;
                    </button>
                </td>
            </tr>
        }

    </table>
    <input type="submit" class="btn btn-success" value="Summary"/>
    }

   @Html.Partial("Summary")
}
else
{
        <p>You don't have shopping card! Go to products and order something!</p>
        }


@section Scripts
{
    @if (ViewBag.Modal == true)
    {
        <script>
            $('#myModal').modal();
        </script>
    }
}

WebStoreProject/WebStoreProject/Views/ShoppingCart/Summary.cshtml
@using WebStoreProject.Models;

<div class="modal fade" id="myModal" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Summary</h4>
            </div>
            <div class="modal-body">
                <table class="table">
                    <tr>
                        <th>
                            @Html.DisplayName("Product name")
                        </th>
                        <th>
                            @Html.DisplayName("Quantity")
                        </th>
                        <th>
                            @Html.DisplayName("Price")
                        </th>
                    </tr>

                    @foreach (var cart in (List<ShoppingCart>)Session["Cart"])
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => cart.Product.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => cart.Quantity)
                            </td>
                            <td>
                                @{
                                    var brutto = String.Format("{0:N2}", @cart.Product.Price_brutto * @cart.Quantity);
                                    if (User.Identity.IsAuthenticated)
                                    {
                                        using (DBModel db = new DBModel())
                                        {
                                            ApplicationUser user = db.Users.Where(u => u.Email.Equals(User.Identity.Name)).First(); user = db.Users.Where(u => u.Email.Equals(User.Identity.Name)).First();
                                            if (user.Price_display.Equals("NETTO"))
                                            {
                                                int? vat = 0;
                                                Product originalProduct = db.Product.Include("VAT").Where(s => s.Id == cart.Product.Id).FirstOrDefault();
                                                if(originalProduct.Vat != null)
                                                {
                                                    vat = originalProduct.Vat.Value;
                                                }
                                                var netto = String.Format("{0:N2}", ((originalProduct.Price_brutto / (100 + vat)) * 100) * cart.Quantity);
                                                @netto
                                            }
                                            else
                                            {
                                                @brutto
                                            }
                                        }
                                    }
                                    else
                                    {
                                        @brutto
                                    }
                                }
                            </td>
                        </tr>
                                    }
                    <tr>
                        <td colspan="2"></td>
                        <td>
                            @{
                                List<ShoppingCart> temp = (List<ShoppingCart>)Session["Cart"];
                                var totalBrutto = String.Format("{0:N2}", temp.Sum(x => x.Product.Price_brutto * x.Quantity));
                                if (User.Identity.IsAuthenticated)
                                {
                                    using (DBModel db = new DBModel())
                                    {
                                        ApplicationUser user = db.Users.Where(u => u.Email.Equals(User.Identity.Name)).First();
                                        if (user.Price_display.Equals("NETTO"))
                                        {
                                            temp.ForEach(x =>
                                            {
                                                x.Product = db.Product.Find(x.Product.Id);
                                                if(x.Product.Vat == null)
                                                {
                                                    x.Product.Vat = new VAT();
                                                    x.Product.Vat.Value = 0;
                                                }
                                            });
                                            var totalnetto = String.Format("{0:N2}", temp.Sum(x => ((x.Product.Price_brutto / (100 + x.Product.Vat.Value)) * 100) * x.Quantity));
                                            @totalnetto
                                        }
                                        else
                                        {
                                            @totalBrutto
                                        }
                                    }
                                }
                                else
                                {
                                    @totalBrutto
                                }
                            }
                        </td>
                    </tr>

                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Index", "Order")'">
                    <i class="fa fa-credit-card" aria-hidden="true"></i>
                    Purchase
                </button>
            </div>
        </div>
    </div>
</div>